# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
env:
  BUILD_TARGET: 'production'
jobs:
  build_site:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: build
        env:
          BASE_PATH: '/siwf'
        run: |
          pnpm run build
      - name: structure
        run: |
          mkdir siwf
          touch siwf/.nojekyll
          mkdir siwf/example
          mkdir siwf/ui
          mv ./packages/ui/build/* ./siwf/ui
          mv ./packages/example/build/* ./siwf/example

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          # this should match the `pages` option in adapter-static options
          path: 'siwf/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
